import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './layout/navbar';
import Script from 'next/script';
import Footer from './layout/footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'porto',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <header className="absolute left-0 top-0 z-50">
          <Navbar />
        </header>
        <main className="min-h-screen">{children}</main>
        <footer>
          <Footer />
        </footer>
        <Script
          crossOrigin="anonymous"
          type="module"
          src="https://unpkg.com/ionicons@latest/dist/ionicons/ionicons.esm.js"
          async
        ></Script>
        <Script
          crossOrigin="anonymous"
          type="module"
          src="https://unpkg.com/ionicons@latest/dist/ionicons/ionicons.js"
          async
        ></Script>
      </body>
    </html>
  );
}
