import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './layout/navbar';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'porto',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <header className="absolute left-0 top-0 z-50">
          <Navbar />
        </header>
        <main className="min-h-screen mt-20 layout">{children}</main>
        <footer className="h-5 bg-secondary"></footer>
        <script
          type="module"
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
          async
        ></script>
        <script
          noModule
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
          async
        ></script>
      </body>
    </html>
  );
}
